# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='slot',
            name='presenter',
        ),
        migrations.AddField(
            model_name='slot',
            name='presenter',
            field=models.ManyToManyField(to='archive.Presenter'),
        ),
    ]
