# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20181203_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slug',
            field=models.CharField(default='bailer', max_length=100),
            preserve_default=False,
        ),
    ]
