# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_slot_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
