# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_presenter_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='attendees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
