# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_slot_poster_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
