# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20181218_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='slug',
            field=models.CharField(default='brian-suda', max_length=200),
            preserve_default=False,
        ),
    ]
