# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_presenter_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='presenter',
            name='country',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presenter',
            name='sex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presenter',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='presenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Presenter'),
        ),
    ]
