# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_slot_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='country',
            field=models.CharField(max_length=12),
        ),
    ]
